APPEND_BODY:
	PUSH(FP);
	MOV(FP,SP);
	PUSH(R1);
	PUSH(R2);
	PUSH(R3);
	PUSH(R4);

	/*the list closure*/
	MOV(R4, INDD(R15,17));
	MOV(R4, INDD(R4,1));
	/*number of arguments*/
	MOV(R2,FPARG(1));
	MOV(R1,IMM(2));
	MOV(R0,IMM(2));
	CMP(R2,0);
	JUMP_EQ(END_APPEND);
	INCR(R2);
	MOV(R1,FPARG(R2));
	MOV(R0,R1);
	DECR(R2);

APPEND_LOOP:
	CMP(R2,IMM(1));
	JUMP_EQ(END_APPEND);
	PUSH(FPARG(R2));
	/*push 'list' closure*/
	PUSH(R4);
	PUSH(IMM(2));
	PUSH(IMM(0));
	CALL(APPLY_BODY);
	DROP(4);
	MOV(R3,R0);
GET_TO_END_OF_LIST:
	CMP(R3,IMM(0));
	JUMP_EQ(DECR_APPEND_LOOP);
	CMP(INDD(R3,2),IMM(2));
	JUMP_EQ(AT_THE_END_OF_LIST);
	MOV(R3,INDD(R3,2));
	JUMP(GET_TO_END_OF_LIST);

AT_THE_END_OF_LIST:
	MOV(INDD(R3,2), R1);
	MOV(R1,R0);

DECR_APPEND_LOOP:
	DECR(R2);
	JUMP(APPEND_LOOP);


END_APPEND:

	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
	RETURN;