BOOLEAN_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_BOOLEAN_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_BOOLEAN_IDENTIFIER:

	CMP(IND(FPARG(2)),T_BOOL);
	JUMP_EQ(IS_BOOLEAN);
NOT_BOOLEAN:
	MOV(R0,IMM(3));
	JUMP(END_BOOL);
IS_BOOLEAN:
	MOV(R0,IMM(5));	
END_BOOL:
	MOV(SP,FP);
	POP(FP);
	RETURN;