
CAR_BODY:
	PUSH(FP);
	MOV(FP,SP);
	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_CAR);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_CAR:

	MOV(R0,INDD(FPARG(2),1));
	
	MOV(SP,FP);
	POP(FP);
	RETURN;