
CHAR_TO_INTEGER_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_CHAR_TO_INTEGER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_CHAR_TO_INTEGER:
	
	MOV(R0,FPARG(2));
	PUSH(INDD(R0,1));
	CALL(MAKE_SOB_INTEGER);
	DROP(1);
	
	MOV(SP,FP);
	POP(FP);
	RETURN;