
GREATER_THEN_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(0));
	JUMP_NE(GOT_ENOUGH_ARGS_GREATER);
	PUSH(FPARG(1));
	PUSH(IMM(2));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_GREATER:
	PUSH(R1);
	PUSH(R2); 
	PUSH(R3);
	PUSH(R4);
	PUSH(R5);
	PUSH(R6);
	PUSH(R7);
	PUSH(R8);
	MOV(R1,IMM(2));
	MOV(R2,IMM(3));
	MOV(R3,FPARG(1));
	ADD(R3,2);

	MOV(R0,IMM(5));
GREATER_VARIADIC_LOOP:
	CMP(R2,R3);
	JUMP_EQ(END_GREATER_VARIDIC_LOOP);	
	PUSH(FPARG(R2));
	PUSH(FPARG(R1));
	CALL(GREATER_TWO_INT);
	DROP(2);
	CMP(R0,IMM(5));
	JUMP_NE(END_GREATER_VARIDIC_LOOP);
	INCR(R1);
	INCR(R2);
	JUMP(GREATER_VARIADIC_LOOP);
END_GREATER_VARIDIC_LOOP:
	
	POP(R8);
	POP(R7);
	POP(R6);
	POP(R5);
	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);

	MOV(SP,FP);
	POP(FP);
	RETURN;


GREATER_TWO_INT:
	PUSH(FP);
	MOV(FP,SP);
	MOV(R0,IMM(5));

	MOV(R5,FPARG(0));
	MOV(R6,FPARG(1));
MAKE_GREATER_FRACTION_1:
	CMP(IND(R5),T_INTEGER);
	JUMP_NE(MAKE_GREATER_FRACTION_2);
	PUSH(IMM(1));
	PUSH(INDD(R5,1));
	CALL(MAKE_SOB_FRACTION);
	MOV(R5,R0);
	DROP(2);
MAKE_GREATER_FRACTION_2:
	CMP(IND(R6),T_INTEGER);
	JUMP_NE(COMPARE_GREATER);
	PUSH(IMM(1));
	PUSH(INDD(R6,1));
	CALL(MAKE_SOB_FRACTION);
	MOV(R6,R0);
	DROP(2);
COMPARE_GREATER:
	MOV(R0,IMM(5));
	MOV(R7,INDD(R5,1));
	MOV(R8,INDD(R6,1));

	MUL(R7,INDD(R6,2));
	MUL(R8,INDD(R5,2));
	CMP(R7,R8);
	JUMP_GT(ARE_GREATER);
	MOV(R0,IMM(3));

ARE_GREATER:
	MOV(SP,FP);
	POP(FP);
	RETURN;






