	
INTEGER_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);
	
	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_INTEGER_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_INTEGER_IDENTIFIER:

	CMP(IND(FPARG(2)),T_INTEGER);
	JUMP_EQ(IS_NUMBER);
NOT_INTEGER:
	MOV(R0,IMM(3));
	JUMP(END_INTEGER_IDENTIFIER_BODY);
IS_INTEGER:
	MOV(R0,IMM(5));	

END_INTEGER_IDENTIFIER_BODY:
	MOV(SP,FP);
	POP(FP);
	RETURN;