MAKE_VECTOR_BODY:
	PUSH(FP);
	MOV(FP,SP);
	PUSH(R1);
	PUSH(R2);
	PUSH(R3);
	PUSH(R4);
	MOV(R1,FPARG(1));	/*should tell it its 2 arguments or 1*/
	CMP(R1,IMM(1));
	JUMP_EQ(ONE_ARG);
	MOV(R3,FPARG(3));
	JUMP(CONT_VEC);
ONE_ARG:
	PUSH(0);
	CALL(MAKE_SOB_INTEGER);
	DROP(1);
	MOV(R3,R0);
CONT_VEC:
	MOV(R2,FPARG(2));
	MOV(R2,INDD(R2,1));
	MOV(R4,R2);


VECTOR_LOOP:
	CMP(R2,IMM(0));
	JUMP_EQ(END_VECTOR_LOOP);
	PUSH(IMM(R3));
	DECR(R2);
	JUMP(VECTOR_LOOP);	

END_VECTOR_LOOP:
	PUSH(R4);
	CALL(MAKE_SOB_VECTOR);
	DROP(1);
	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
	RETURN;
