
NUMBER_SUBSTRACTION_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_GE(GOT_ENOUGH_ARGS_SUBSTRACTION);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_SUBSTRACTION:
	PUSH(R1);
	PUSH(R2); 
	PUSH(R3);
	PUSH(R4);
	PUSH(R5);
	PUSH(R6);
	PUSH(R7);
	PUSH(R8);
	CMP(FPARG(1), IMM(1));
	JUMP_NE(MORE_THAN_ONE);
	MOV(R0,FPARG(2));
	CMP(IND(R0),T_FRACTION);
	JUMP_EQ(IS_ONE_AND_FRACTION);
	PUSH(IMM(-1));
	PUSH(INDD(R0,1));
	CALL(MAKE_SOB_FRACTION_REDUCT);
	DROP(2);
	JUMP(END_NUMBER_SUBSTRACTION);

IS_ONE_AND_FRACTION:
	MOV(R1,INDD(R0,1));
	MOV(R2,INDD(R0,2));
	MUL(R1,IMM(-1));
	PUSH(R2);
	PUSH(R1);
	CALL(MAKE_SOB_FRACTION_REDUCT);
	DROP(2);
	JUMP(END_NUMBER_SUBSTRACTION);

MORE_THAN_ONE:
	MOV(R1,IMM(3));/*R1 IS THE INDEX*/
	MOV(R3,FPARG(1));/*R3 HOLDS THE NUMBER OF ARGUMENTS*/
	ADD(R3,2);
	MOV(R5,FPARG(2));
	CMP(IND(R5),T_INTEGER);
	JUMP_NE(SUBSTRACTION_VARIADIC_LOOP);
	PUSH(IMM(1));
	PUSH(INDD(R5,1));
	CALL(MAKE_SOB_FRACTION);
	MOV(R5,R0); /*R5 IS THE ACCUMULATOR*/
	DROP(2);
SUBSTRACTION_VARIADIC_LOOP:
	CMP(R1,R3);
	JUMP_EQ(END_SUBSTRACTION_VARIDIC_LOOP);	
	PUSH(FPARG(R1));
	CALL(SUBSTRACTION);
	DROP(1);
	INCR(R1);
	JUMP(SUBSTRACTION_VARIADIC_LOOP);
END_SUBSTRACTION_VARIDIC_LOOP:
	PUSH(INDD(R5,2));
	PUSH(INDD(R5,1));
	CALL(MAKE_SOB_FRACTION_REDUCT);

END_NUMBER_SUBSTRACTION:
	POP(R8);
	POP(R7);
	POP(R6);
	POP(R5);
	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);

	MOV(SP,FP);
	POP(FP);
	RETURN;

SUBSTRACTION:
	PUSH(FP);
	MOV(FP,SP);
	PUSH(R1);
	PUSH(R2);
	PUSH(R3);
	PUSH(R4);
	PUSH(R6);

MAKE_SUBSTRACTION_FRACTION:
	MOV(R1,FPARG(0));
	CMP(IND(R1),T_INTEGER);
	JUMP_NE(SUBSTRACTION_1);
	PUSH(IMM(1));
	PUSH(INDD(R1,1));
	CALL(MAKE_SOB_FRACTION);
	MOV(R1,R0);
	DROP(2);
SUBSTRACTION_1:
	MOV(R2,INDD(R5,1));
	MOV(R3,INDD(R5,2));
	MOV(R4,INDD(R1,1));
	MOV(R6,INDD(R1,2));
	MUL(R2,R6);
	MUL(R4,R3);
	SUB(R2,R4);

	MUL(R3,R6);

	PUSH(R3);
	PUSH(R2);
	CALL(MAKE_SOB_FRACTION);
	DROP(2);
	MOV(R5,R0);
	POP(R6);
	POP(R4);
	POP(R3);
	POP(R2);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
	RETURN;
