
PAIR_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);
	
	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_PAIR_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_PAIR_IDENTIFIER:

	MOV(R0,IND(FPARG(2)));
	CMP(R0,T_PAIR);
	JUMP_EQ(IS_PAIR);

NOT_PAIR:
	MOV(R0,IMM(3));
	JUMP(END_PAIR_IDENTIFIER_BODY);

IS_PAIR:
	MOV(R0,IMM(5));

END_PAIR_IDENTIFIER_BODY:

	MOV(SP,FP);
	POP(FP);
	RETURN;