
PROCEDURE_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);
	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_PROCEDURE_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_PROCEDURE_IDENTIFIER:
	
	MOV(R0,IND(FPARG(2)));
	CMP(R0,T_CLOSURE);
	JUMP_EQ(IS_PROC);

NOT_PROC:
	MOV(R0,IMM(3));
	JUMP(END_PROCEDURE_IDENTIFIER_BODY);

IS_PROC:
	MOV(R0,IMM(5));

END_PROCEDURE_IDENTIFIER_BODY:

	MOV(SP,FP);
	POP(FP);
	RETURN;