
STRING_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_STRING_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_STRING_IDENTIFIER:

	MOV(R0,IND(FPARG(2)));
	CMP(R0,T_STRING);
	JUMP_EQ(IS_STRING);

NOT_STRING:
	MOV(R0,IMM(3));
	JUMP(END_STRING_IDENTIFIER_BODY);

IS_STRING:
	MOV(R0,IMM(5));

END_STRING_IDENTIFIER_BODY:

	MOV(SP,FP);
	POP(FP);
	RETURN;