
VECTOR_LENGTH_BODY:
	PUSH(FP);
	MOV(FP,SP);
	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_VECTOR_LENGTH);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_VECTOR_LENGTH:

	MOV(R0,FPARG(2));
	MOV(R0, INDD(R0,1));
	PUSH(R0);
	CALL(MAKE_SOB_INTEGER);
	DROP(1);

	MOV(SP,FP);
	POP(FP);
	RETURN;