
VECTOR_REF_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(2));
	JUMP_EQ(GOT_ENOUGH_ARGS_VECTOR_REF);
	PUSH(FPARG(1));
	PUSH(IMM(2));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_VECTOR_REF:
	PUSH(R1);
	MOV(R0,FPARG(2));
	MOV(R1,FPARG(3));
	MOV(R1,INDD(R1,1));
	ADD(R1,IMM(2));
	MOV(R0,INDD(R0,R1));

	POP(R1);
	MOV(SP,FP);
	POP(FP);
	RETURN;