
VECTOR_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_VECTOR_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_VECTOR_IDENTIFIER:

	MOV(R0, FPARG(2));
	CMP(IND(R0), T_VECTOR);
	JUMP_EQ(IS_VECTOR);
	MOV(R0,3);
	JUMP(END_VECTOR_IDENTIFIER);
IS_VECTOR:
	MOV(R0,5);

END_VECTOR_IDENTIFIER:

	MOV(SP,FP);
	POP(FP);
	RETURN;