
ZERO_IDENTIFIER_BODY:
	PUSH(FP);
	MOV(FP,SP);

	CMP(FPARG(1), IMM(1));
	JUMP_EQ(GOT_ENOUGH_ARGS_ZERO_IDENTIFIER);
	PUSH(FPARG(1));
	PUSH(IMM(1));
	CALL(THROW_WRONG_NUMBER_OF_ARGS);

GOT_ENOUGH_ARGS_ZERO_IDENTIFIER:
	PUSH(R1);
	MOV(R0,5);
	MOV(R1,FPARG(2));
	MOV(R1,INDD(R1,1));
	CMP(R1, IMM(0));
	JUMP_EQ(END_ZERO_IDENTIFIER);
	MOV(R0,IMM(3));

END_ZERO_IDENTIFIER:

	POP(R1);
	MOV(SP,FP);
	POP(FP);
	RETURN;